# Generated by Django 4.1 on 2022-09-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watclistMovies',
            new_name='WatchlistMovies',
        ),
    ]
