# Generated by Django 4.1 on 2022-09-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_watclistmovies_watchlistmovies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistmovies',
            name='rating',
            field=models.FloatField(),
        ),
    ]
