# Generated by Django 4.1 on 2022-09-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_watchlistmovies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistmovies',
            name='watched',
            field=models.TextField(),
        ),
    ]
