# Generated by Django 4.1 on 2022-09-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0004_alter_watchlistmovies_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistmovies',
            name='watched',
            field=models.CharField(max_length=10),
        ),
    ]
