# Generated by Django 4.1 on 2022-09-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0005_alter_watchlistmovies_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlistmovies',
            old_name='watched',
            new_name='is_watched',
        ),
    ]
